# Generated by Django 3.2 on 2021-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading1', models.CharField(max_length=75)),
                ('conthead1', models.CharField(max_length=1000)),
                ('heading2', models.CharField(max_length=75)),
                ('conthead2', models.CharField(max_length=1000)),
                ('heading3', models.CharField(max_length=75)),
                ('conthead3', models.CharField(max_length=1000)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=60)),
                ('image', models.ImageField(default='', upload_to='blog/images')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
